- block:
  # install software
  - import_tasks: software/packages_development.yml
  - import_tasks: software/inst_docker.yml
  - import_tasks: software/packages_utilities.yml
  - import_tasks: software/packages_cleanup.yml
  
  rescue:
    - set_fact: task_failed=true

